import mongoose from "mongoose";
import sharp from "sharp";

import "../loadEnvironments.js";
import UserModel from "../models/User.model.js";
import ProductModel from "../models/Product.model.js";
import SellerModel from "../models/Seller.model.js";
import { uploadFiles } from "../s3.js";

const TYPE_COLORS = {
  processor: { r: 59, g: 130, b: 246, alpha: 1 },
  motherboard: { r: 16, g: 185, b: 129, alpha: 1 },
  ram: { r: 244, g: 114, b: 182, alpha: 1 },
  storage: { r: 251, g: 191, b: 36, alpha: 1 },
  psu: { r: 248, g: 113, b: 113, alpha: 1 },
  gpu: { r: 139, g: 92, b: 246, alpha: 1 },
  cooling: { r: 56, g: 189, b: 248, alpha: 1 },
  case: { r: 163, g: 163, b: 163, alpha: 1 },
};

const DATA = {
  processor: [
    {
      name: "Intel Core i5-13600K",
      price: 320,
      specs: {
        cores: { performance: 6, efficiency: 8, threads: 20 },
        clock: { base: 3.5, boost: 5.1 },
        socket: "LGA1700",
        tdp: 125,
        memory: { type: "DDR5", maxSpeed: 5600, maxCapacity: 128, channels: 2 },
        cache: { l2: 20, l3: 24 },
        architecture: "x86-64",
        integratedGraphics: "Intel UHD 770",
        pcie: { version: "5.0", lanes: 20 },
      },
    },
    {
      name: "Intel Core i7-13700K",
      price: 420,
      specs: {
        cores: { performance: 8, efficiency: 8, threads: 24 },
        clock: { base: 3.4, boost: 5.4 },
        socket: "LGA1700",
        tdp: 125,
        memory: { type: "DDR5", maxSpeed: 5600, maxCapacity: 128, channels: 2 },
        cache: { l2: 30, l3: 30 },
        architecture: "x86-64",
        integratedGraphics: "Intel UHD 770",
        pcie: { version: "5.0", lanes: 20 },
      },
    },
    {
      name: "Intel Core i9-13900K",
      price: 580,
      specs: {
        cores: { performance: 8, efficiency: 16, threads: 32 },
        clock: { base: 3.0, boost: 5.8 },
        socket: "LGA1700",
        tdp: 125,
        memory: { type: "DDR5", maxSpeed: 5600, maxCapacity: 128, channels: 2 },
        cache: { l2: 32, l3: 36 },
        architecture: "x86-64",
        integratedGraphics: "Intel UHD 770",
        pcie: { version: "5.0", lanes: 20 },
      },
    },
    {
      name: "AMD Ryzen 5 7600X",
      price: 250,
      specs: {
        cores: { performance: 6, efficiency: 0, threads: 12 },
        clock: { base: 4.7, boost: 5.3 },
        socket: "AM5",
        tdp: 105,
        memory: { type: "DDR5", maxSpeed: 5200, maxCapacity: 128, channels: 2 },
        cache: { l2: 6, l3: 32 },
        architecture: "x86-64",
        integratedGraphics: "AMD Radeon Graphics",
        pcie: { version: "5.0", lanes: 24 },
      },
    },
    {
      name: "AMD Ryzen 7 7800X3D",
      price: 450,
      specs: {
        cores: { performance: 8, efficiency: 0, threads: 16 },
        clock: { base: 4.2, boost: 5.0 },
        socket: "AM5",
        tdp: 120,
        memory: { type: "DDR5", maxSpeed: 5200, maxCapacity: 128, channels: 2 },
        cache: { l2: 8, l3: 96 },
        architecture: "x86-64",
        integratedGraphics: "AMD Radeon Graphics",
        pcie: { version: "5.0", lanes: 24 },
      },
    },
    {
      name: "AMD Ryzen 9 7950X",
      price: 620,
      specs: {
        cores: { performance: 16, efficiency: 0, threads: 32 },
        clock: { base: 4.5, boost: 5.7 },
        socket: "AM5",
        tdp: 170,
        memory: { type: "DDR5", maxSpeed: 5200, maxCapacity: 128, channels: 2 },
        cache: { l2: 16, l3: 64 },
        architecture: "x86-64",
        integratedGraphics: "AMD Radeon Graphics",
        pcie: { version: "5.0", lanes: 24 },
      },
    },
    {
      name: "Intel Core i5-12400F",
      price: 170,
      specs: {
        cores: { performance: 6, efficiency: 0, threads: 12 },
        clock: { base: 2.5, boost: 4.4 },
        socket: "LGA1700",
        tdp: 65,
        memory: { type: "DDR4", maxSpeed: 3200, maxCapacity: 128, channels: 2 },
        cache: { l2: 7.5, l3: 18 },
        architecture: "x86-64",
        integratedGraphics: "None",
        pcie: { version: "4.0", lanes: 16 },
      },
    },
    {
      name: "AMD Ryzen 5 5600",
      price: 140,
      specs: {
        cores: { performance: 6, efficiency: 0, threads: 12 },
        clock: { base: 3.5, boost: 4.4 },
        socket: "AM4",
        tdp: 65,
        memory: { type: "DDR4", maxSpeed: 3200, maxCapacity: 128, channels: 2 },
        cache: { l2: 3, l3: 32 },
        architecture: "x86-64",
        integratedGraphics: "None",
        pcie: { version: "3.0", lanes: 24 },
      },
    },
    {
      name: "Intel Core i3-13100",
      price: 130,
      specs: {
        cores: { performance: 4, efficiency: 0, threads: 8 },
        clock: { base: 3.4, boost: 4.5 },
        socket: "LGA1700",
        tdp: 60,
        memory: { type: "DDR5", maxSpeed: 4800, maxCapacity: 128, channels: 2 },
        cache: { l2: 5, l3: 12 },
        architecture: "x86-64",
        integratedGraphics: "Intel UHD 730",
        pcie: { version: "4.0", lanes: 20 },
      },
    },
    {
      name: "AMD Ryzen 9 9950X",
      price: 680,
      specs: {
        cores: { performance: 16, efficiency: 0, threads: 32 },
        clock: { base: 4.3, boost: 5.7 },
        socket: "AM5",
        tdp: 170,
        memory: { type: "DDR5", maxSpeed: 5600, maxCapacity: 192, channels: 2 },
        cache: { l2: 16, l3: 64 },
        architecture: "x86-64",
        integratedGraphics: "AMD Radeon Graphics",
        pcie: { version: "5.0", lanes: 28 },
      },
    },
  ],

  motherboard: [
    {
      name: "ASUS ROG Strix Z790-E Gaming",
      price: 480,
      specs: {
        socket: "LGA1700",
        chipset: "Z790",
        formFactor: "ATX",
        memory: { type: "DDR5", maxSpeed: 7800, maxCapacity: 256, slots: 4 },
        pci: { version: "PCIe 5.0", x16Slots: 2, x1Slots: 3 },
        storage: { sataPorts: 6, m2Slots: 4, raidSupport: true },
        power: { cpuPowerConnector: "8+4-pin", phases: 18 },
        networking: { ethernetSpeed: "2.5Gb", wifi: true, bluetooth: true },
        usb: { usb2: 2, usb3: 8, usbC: 2 },
        audio: { channels: "7.1", chipset: "ALC4082" },
      },
    },
    {
      name: "MSI MAG B760 Tomahawk",
      price: 220,
      specs: {
        socket: "LGA1700",
        chipset: "B760",
        formFactor: "ATX",
        memory: { type: "DDR5", maxSpeed: 7200, maxCapacity: 192, slots: 4 },
        pci: { version: "PCIe 4.0", x16Slots: 2, x1Slots: 2 },
        storage: { sataPorts: 6, m2Slots: 3, raidSupport: true },
        power: { cpuPowerConnector: "8+4-pin", phases: 14 },
        networking: { ethernetSpeed: "2.5Gb", wifi: false, bluetooth: false },
        usb: { usb2: 4, usb3: 6, usbC: 1 },
        audio: { channels: "7.1", chipset: "ALC4080" },
      },
    },
    {
      name: "Gigabyte B650 Aorus Elite AX",
      price: 230,
      specs: {
        socket: "AM5",
        chipset: "B650",
        formFactor: "ATX",
        memory: { type: "DDR5", maxSpeed: 6400, maxCapacity: 128, slots: 4 },
        pci: { version: "PCIe 4.0", x16Slots: 2, x1Slots: 2 },
        storage: { sataPorts: 4, m2Slots: 3, raidSupport: true },
        power: { cpuPowerConnector: "8+4-pin", phases: 12 },
        networking: { ethernetSpeed: "2.5Gb", wifi: true, bluetooth: true },
        usb: { usb2: 2, usb3: 7, usbC: 1 },
        audio: { channels: "7.1", chipset: "ALC1220" },
      },
    },
    {
      name: "ASUS TUF Gaming X670E-Plus",
      price: 370,
      specs: {
        socket: "AM5",
        chipset: "X670E",
        formFactor: "ATX",
        memory: { type: "DDR5", maxSpeed: 7200, maxCapacity: 128, slots: 4 },
        pci: { version: "PCIe 5.0", x16Slots: 2, x1Slots: 3 },
        storage: { sataPorts: 4, m2Slots: 4, raidSupport: true },
        power: { cpuPowerConnector: "8+4-pin", phases: 18 },
        networking: { ethernetSpeed: "2.5Gb", wifi: true, bluetooth: true },
        usb: { usb2: 2, usb3: 8, usbC: 2 },
        audio: { channels: "7.1", chipset: "ALC4080" },
      },
    },
    {
      name: "MSI PRO B550M-VC",
      price: 95,
      specs: {
        socket: "AM4",
        chipset: "B550",
        formFactor: "Micro-ATX",
        memory: { type: "DDR4", maxSpeed: 4400, maxCapacity: 64, slots: 4 },
        pci: { version: "PCIe 4.0", x16Slots: 1, x1Slots: 2 },
        storage: { sataPorts: 4, m2Slots: 1, raidSupport: false },
        power: { cpuPowerConnector: "8-pin", phases: 8 },
        networking: { ethernetSpeed: "1Gb", wifi: false, bluetooth: false },
        usb: { usb2: 2, usb3: 4, usbC: 0 },
        audio: { channels: "5.1", chipset: "ALC897" },
      },
    },
    {
      name: "ASRock Z790 Pro RS",
      price: 210,
      specs: {
        socket: "LGA1700",
        chipset: "Z790",
        formFactor: "ATX",
        memory: { type: "DDR5", maxSpeed: 7000, maxCapacity: 192, slots: 4 },
        pci: { version: "PCIe 5.0", x16Slots: 2, x1Slots: 2 },
        storage: { sataPorts: 6, m2Slots: 3, raidSupport: true },
        power: { cpuPowerConnector: "8+4-pin", phases: 14 },
        networking: { ethernetSpeed: "1Gb", wifi: false, bluetooth: false },
        usb: { usb2: 4, usb3: 6, usbC: 1 },
        audio: { channels: "7.1", chipset: "ALC897" },
      },
    },
    {
      name: "Gigabyte X570 Aorus Pro",
      price: 250,
      specs: {
        socket: "AM4",
        chipset: "X570",
        formFactor: "ATX",
        memory: { type: "DDR4", maxSpeed: 4400, maxCapacity: 128, slots: 4 },
        pci: { version: "PCIe 4.0", x16Slots: 2, x1Slots: 2 },
        storage: { sataPorts: 6, m2Slots: 2, raidSupport: true },
        power: { cpuPowerConnector: "8+8-pin", phases: 14 },
        networking: { ethernetSpeed: "1Gb", wifi: true, bluetooth: true },
        usb: { usb2: 4, usb3: 7, usbC: 1 },
        audio: { channels: "7.1", chipset: "ALC1220-VB" },
      },
    },
    {
      name: "ASUS ROG Strix B650E-I",
      price: 320,
      specs: {
        socket: "AM5",
        chipset: "B650E",
        formFactor: "Mini-ITX",
        memory: { type: "DDR5", maxSpeed: 6400, maxCapacity: 64, slots: 2 },
        pci: { version: "PCIe 5.0", x16Slots: 1, x1Slots: 0 },
        storage: { sataPorts: 2, m2Slots: 2, raidSupport: false },
        power: { cpuPowerConnector: "8-pin", phases: 10 },
        networking: { ethernetSpeed: "2.5Gb", wifi: true, bluetooth: true },
        usb: { usb2: 0, usb3: 6, usbC: 2 },
        audio: { channels: "5.1", chipset: "ALC4080" },
      },
    },
    {
      name: "MSI MPG Z690 Carbon WiFi",
      price: 350,
      specs: {
        socket: "LGA1700",
        chipset: "Z690",
        formFactor: "ATX",
        memory: { type: "DDR5", maxSpeed: 6666, maxCapacity: 128, slots: 4 },
        pci: { version: "PCIe 5.0", x16Slots: 2, x1Slots: 2 },
        storage: { sataPorts: 6, m2Slots: 4, raidSupport: true },
        power: { cpuPowerConnector: "8+4-pin", phases: 16 },
        networking: { ethernetSpeed: "2.5Gb", wifi: true, bluetooth: true },
        usb: { usb2: 2, usb3: 7, usbC: 2 },
        audio: { channels: "7.1", chipset: "ALC4080" },
      },
    },
    {
      name: "Biostar B450MH",
      price: 60,
      specs: {
        socket: "AM4",
        chipset: "B450",
        formFactor: "Micro-ATX",
        memory: { type: "DDR4", maxSpeed: 3200, maxCapacity: 32, slots: 2 },
        pci: { version: "PCIe 3.0", x16Slots: 1, x1Slots: 1 },
        storage: { sataPorts: 4, m2Slots: 1, raidSupport: false },
        power: { cpuPowerConnector: "4-pin", phases: 4 },
        networking: { ethernetSpeed: "1Gb", wifi: false, bluetooth: false },
        usb: { usb2: 4, usb3: 2, usbC: 0 },
        audio: { channels: "5.1", chipset: "ALC662" },
      },
    },
  ],

  ram: [
    {
      name: "Corsair Vengeance DDR5 32GB (2x16GB) 6000MHz",
      price: 95,
      specs: {
        type: "DDR5",
        formFactor: "DIMM",
        capacity: 32,
        speed: 6000,
        latency: { cl: 36, trcd: 36, trp: 36, tras: 76 },
        voltage: 1.35,
        ecc: false,
        sticks: 2,
      },
    },
    {
      name: "G.Skill Trident Z5 RGB DDR5 32GB (2x16GB) 6400MHz",
      price: 110,
      specs: {
        type: "DDR5",
        formFactor: "DIMM",
        capacity: 32,
        speed: 6400,
        latency: { cl: 32, trcd: 39, trp: 39, tras: 102 },
        voltage: 1.4,
        ecc: false,
        sticks: 2,
      },
    },
    {
      name: "Kingston Fury Beast DDR4 16GB (2x8GB) 3200MHz",
      price: 45,
      specs: {
        type: "DDR4",
        formFactor: "DIMM",
        capacity: 16,
        speed: 3200,
        latency: { cl: 16, trcd: 18, trp: 18, tras: 36 },
        voltage: 1.35,
        ecc: false,
        sticks: 2,
      },
    },
    {
      name: "Corsair Dominator Platinum DDR5 64GB (2x32GB) 6000MHz",
      price: 220,
      specs: {
        type: "DDR5",
        formFactor: "DIMM",
        capacity: 64,
        speed: 6000,
        latency: { cl: 30, trcd: 36, trp: 36, tras: 76 },
        voltage: 1.4,
        ecc: false,
        sticks: 2,
      },
    },
    {
      name: "TeamGroup T-Force Delta RGB DDR4 32GB (2x16GB) 3600MHz",
      price: 70,
      specs: {
        type: "DDR4",
        formFactor: "DIMM",
        capacity: 32,
        speed: 3600,
        latency: { cl: 18, trcd: 22, trp: 22, tras: 42 },
        voltage: 1.35,
        ecc: false,
        sticks: 2,
      },
    },
    {
      name: "G.Skill Ripjaws V DDR4 16GB (2x8GB) 3600MHz",
      price: 42,
      specs: {
        type: "DDR4",
        formFactor: "DIMM",
        capacity: 16,
        speed: 3600,
        latency: { cl: 16, trcd: 19, trp: 19, tras: 39 },
        voltage: 1.35,
        ecc: false,
        sticks: 2,
      },
    },
    {
      name: "Corsair Vengeance LPX DDR4 32GB (2x16GB) 3200MHz",
      price: 65,
      specs: {
        type: "DDR4",
        formFactor: "DIMM",
        capacity: 32,
        speed: 3200,
        latency: { cl: 16, trcd: 20, trp: 20, tras: 38 },
        voltage: 1.35,
        ecc: false,
        sticks: 2,
      },
    },
    {
      name: "Kingston Fury Renegade DDR5 32GB (2x16GB) 7200MHz",
      price: 140,
      specs: {
        type: "DDR5",
        formFactor: "DIMM",
        capacity: 32,
        speed: 7200,
        latency: { cl: 38, trcd: 38, trp: 38, tras: 78 },
        voltage: 1.45,
        ecc: false,
        sticks: 2,
      },
    },
    {
      name: "ADATA XPG Lancer DDR5 16GB (2x8GB) 6000MHz",
      price: 58,
      specs: {
        type: "DDR5",
        formFactor: "DIMM",
        capacity: 16,
        speed: 6000,
        latency: { cl: 36, trcd: 36, trp: 36, tras: 76 },
        voltage: 1.35,
        ecc: false,
        sticks: 2,
      },
    },
    {
      name: "Crucial Pro DDR4 16GB (1x16GB) 3200MHz",
      price: 38,
      specs: {
        type: "DDR4",
        formFactor: "DIMM",
        capacity: 16,
        speed: 3200,
        latency: { cl: 22, trcd: 22, trp: 22, tras: 52 },
        voltage: 1.2,
        ecc: false,
        sticks: 1,
      },
    },
  ],

  storage: [
    {
      name: "Samsung 980 Pro 1TB NVMe SSD",
      price: 85,
      specs: {
        type: "NVMe",
        formFactor: "M.2",
        interface: "PCIe 4.0",
        capacity: 1000,
        speed: { read: 7000, write: 5000 },
        cache: 1024,
        tbw: 600,
      },
    },
    {
      name: "WD Black SN850X 2TB NVMe SSD",
      price: 150,
      specs: {
        type: "NVMe",
        formFactor: "M.2",
        interface: "PCIe 4.0",
        capacity: 2000,
        speed: { read: 7300, write: 6600 },
        cache: 2048,
        tbw: 1200,
      },
    },
    {
      name: "Crucial MX500 1TB SSD",
      price: 55,
      specs: {
        type: "SSD",
        formFactor: '2.5"',
        interface: "SATA",
        capacity: 1000,
        speed: { read: 560, write: 510 },
        cache: 0,
        tbw: 360,
      },
    },
    {
      name: "Samsung 870 EVO 2TB SSD",
      price: 110,
      specs: {
        type: "SSD",
        formFactor: '2.5"',
        interface: "SATA",
        capacity: 2000,
        speed: { read: 560, write: 530 },
        cache: 2048,
        tbw: 1200,
      },
    },
    {
      name: "Seagate Barracuda 2TB HDD",
      price: 50,
      specs: {
        type: "HDD",
        formFactor: '3.5"',
        interface: "SATA",
        capacity: 2000,
        speed: { read: 190, write: 190 },
        cache: 256,
        tbw: 0,
      },
    },
    {
      name: "WD Blue 4TB HDD",
      price: 90,
      specs: {
        type: "HDD",
        formFactor: '3.5"',
        interface: "SATA",
        capacity: 4000,
        speed: { read: 180, write: 180 },
        cache: 256,
        tbw: 0,
      },
    },
    {
      name: "Kingston NV2 500GB NVMe SSD",
      price: 35,
      specs: {
        type: "NVMe",
        formFactor: "M.2",
        interface: "PCIe 4.0",
        capacity: 500,
        speed: { read: 3500, write: 2100 },
        cache: 0,
        tbw: 160,
      },
    },
    {
      name: "Sabrent Rocket 4 Plus 4TB NVMe SSD",
      price: 320,
      specs: {
        type: "NVMe",
        formFactor: "M.2",
        interface: "PCIe 4.0",
        capacity: 4000,
        speed: { read: 7100, write: 6600 },
        cache: 4096,
        tbw: 2800,
      },
    },
    {
      name: "Crucial P3 1TB NVMe SSD",
      price: 60,
      specs: {
        type: "NVMe",
        formFactor: "M.2",
        interface: "PCIe 3.0",
        capacity: 1000,
        speed: { read: 3500, write: 3000 },
        cache: 0,
        tbw: 220,
      },
    },
    {
      name: "Seagate FireCuda 530 2TB NVMe SSD",
      price: 180,
      specs: {
        type: "NVMe",
        formFactor: "M.2",
        interface: "PCIe 4.0",
        capacity: 2000,
        speed: { read: 7300, write: 6900 },
        cache: 2048,
        tbw: 1275,
      },
    },
  ],

  psu: [
    {
      name: "Corsair RM850x",
      price: 130,
      specs: {
        wattage: 850,
        formFactor: "ATX",
        efficiency: "80+ Gold",
        modular: "Fully Modular",
        connectors: { eps: 2, pcie8pin: 6, pcie16pin: 1, sata: 8, molex: 4 },
        protection: { ovp: true, uvp: true, ocp: true, opp: true, scp: true, otp: true },
        fanSize: 135,
        length: 160,
      },
    },
    {
      name: "EVGA SuperNOVA 750 G6",
      price: 115,
      specs: {
        wattage: 750,
        formFactor: "ATX",
        efficiency: "80+ Gold",
        modular: "Fully Modular",
        connectors: { eps: 2, pcie8pin: 4, pcie16pin: 0, sata: 6, molex: 3 },
        protection: { ovp: true, uvp: true, ocp: true, opp: true, scp: true, otp: true },
        fanSize: 135,
        length: 150,
      },
    },
    {
      name: "Seasonic Focus GX-650",
      price: 95,
      specs: {
        wattage: 650,
        formFactor: "ATX",
        efficiency: "80+ Gold",
        modular: "Fully Modular",
        connectors: { eps: 1, pcie8pin: 2, pcie16pin: 0, sata: 6, molex: 2 },
        protection: { ovp: true, uvp: true, ocp: true, opp: false, scp: true, otp: true },
        fanSize: 120,
        length: 140,
      },
    },
    {
      name: "be quiet! Straight Power 12 1000W",
      price: 200,
      specs: {
        wattage: 1000,
        formFactor: "ATX",
        efficiency: "80+ Platinum",
        modular: "Fully Modular",
        connectors: { eps: 2, pcie8pin: 6, pcie16pin: 1, sata: 10, molex: 4 },
        protection: { ovp: true, uvp: true, ocp: true, opp: true, scp: true, otp: true },
        fanSize: 135,
        length: 170,
      },
    },
    {
      name: "Cooler Master MWE Gold 650",
      price: 80,
      specs: {
        wattage: 650,
        formFactor: "ATX",
        efficiency: "80+ Gold",
        modular: "Semi-Modular",
        connectors: { eps: 1, pcie8pin: 2, pcie16pin: 0, sata: 6, molex: 2 },
        protection: { ovp: true, uvp: true, ocp: true, opp: false, scp: true, otp: false },
        fanSize: 120,
        length: 140,
      },
    },
    {
      name: "Thermaltake Toughpower GF3 850W",
      price: 140,
      specs: {
        wattage: 850,
        formFactor: "ATX",
        efficiency: "80+ Gold",
        modular: "Fully Modular",
        connectors: { eps: 2, pcie8pin: 6, pcie16pin: 1, sata: 8, molex: 4 },
        protection: { ovp: true, uvp: true, ocp: true, opp: true, scp: true, otp: true },
        fanSize: 140,
        length: 160,
      },
    },
    {
      name: "NZXT C850",
      price: 135,
      specs: {
        wattage: 850,
        formFactor: "ATX",
        efficiency: "80+ Gold",
        modular: "Fully Modular",
        connectors: { eps: 2, pcie8pin: 4, pcie16pin: 1, sata: 8, molex: 4 },
        protection: { ovp: true, uvp: true, ocp: true, opp: true, scp: true, otp: true },
        fanSize: 120,
        length: 160,
      },
    },
    {
      name: "ASUS ROG Thor 1200W",
      price: 280,
      specs: {
        wattage: 1200,
        formFactor: "ATX",
        efficiency: "80+ Platinum",
        modular: "Fully Modular",
        connectors: { eps: 2, pcie8pin: 8, pcie16pin: 1, sata: 10, molex: 4 },
        protection: { ovp: true, uvp: true, ocp: true, opp: true, scp: true, otp: true },
        fanSize: 135,
        length: 180,
      },
    },
    {
      name: "Corsair SF750",
      price: 170,
      specs: {
        wattage: 750,
        formFactor: "SFX",
        efficiency: "80+ Platinum",
        modular: "Fully Modular",
        connectors: { eps: 1, pcie8pin: 2, pcie16pin: 0, sata: 4, molex: 2 },
        protection: { ovp: true, uvp: true, ocp: true, opp: true, scp: true, otp: true },
        fanSize: 92,
        length: 125,
      },
    },
    {
      name: "MSI MPG A750GF",
      price: 100,
      specs: {
        wattage: 750,
        formFactor: "ATX",
        efficiency: "80+ Gold",
        modular: "Fully Modular",
        connectors: { eps: 1, pcie8pin: 4, pcie16pin: 0, sata: 6, molex: 3 },
        protection: { ovp: true, uvp: true, ocp: true, opp: false, scp: true, otp: true },
        fanSize: 120,
        length: 140,
      },
    },
  ],

  gpu: [
    {
      name: "NVIDIA GeForce RTX 4070",
      price: 599,
      specs: {
        memory: { capacity: 12, type: "GDDR6X", bandwidth: 504, bus: 192 },
        clock: { base: 1920, boost: 2475 },
        connector: "PCIe 4.0",
        power: { tdp: 200, connectors: "1x16-pin", recommended: 650 },
        display: { outputs: ["HDMI 2.1", "DisplayPort 1.4a"], maxResolution: "7680x4320", maxDisplays: 4 },
        dimensions: { length: 267, slots: 2 },
        cudaCores: 5888,
        shaderProcessors: 5888,
      },
    },
    {
      name: "NVIDIA GeForce RTX 4080",
      price: 999,
      specs: {
        memory: { capacity: 16, type: "GDDR6X", bandwidth: 717, bus: 256 },
        clock: { base: 2205, boost: 2505 },
        connector: "PCIe 4.0",
        power: { tdp: 320, connectors: "1x16-pin", recommended: 750 },
        display: { outputs: ["HDMI 2.1", "DisplayPort 1.4a"], maxResolution: "7680x4320", maxDisplays: 4 },
        dimensions: { length: 304, slots: 3 },
        cudaCores: 9728,
        shaderProcessors: 9728,
      },
    },
    {
      name: "NVIDIA GeForce RTX 4090",
      price: 1599,
      specs: {
        memory: { capacity: 24, type: "GDDR6X", bandwidth: 1008, bus: 384 },
        clock: { base: 2235, boost: 2520 },
        connector: "PCIe 4.0",
        power: { tdp: 450, connectors: "1x16-pin", recommended: 850 },
        display: { outputs: ["HDMI 2.1", "DisplayPort 1.4a"], maxResolution: "7680x4320", maxDisplays: 4 },
        dimensions: { length: 304, slots: 3 },
        cudaCores: 16384,
        shaderProcessors: 16384,
      },
    },
    {
      name: "NVIDIA GeForce RTX 4060 Ti",
      price: 399,
      specs: {
        memory: { capacity: 8, type: "GDDR6", bandwidth: 288, bus: 128 },
        clock: { base: 2310, boost: 2535 },
        connector: "PCIe 4.0",
        power: { tdp: 160, connectors: "1x8-pin", recommended: 550 },
        display: { outputs: ["HDMI 2.1", "DisplayPort 1.4a"], maxResolution: "7680x4320", maxDisplays: 4 },
        dimensions: { length: 244, slots: 2 },
        cudaCores: 4352,
        shaderProcessors: 4352,
      },
    },
    {
      name: "AMD Radeon RX 7800 XT",
      price: 499,
      specs: {
        memory: { capacity: 16, type: "GDDR6", bandwidth: 624, bus: 256 },
        clock: { base: 1295, boost: 2430 },
        connector: "PCIe 4.0",
        power: { tdp: 263, connectors: "2x8-pin", recommended: 700 },
        display: { outputs: ["HDMI 2.1", "DisplayPort 2.1"], maxResolution: "7680x4320", maxDisplays: 4 },
        dimensions: { length: 287, slots: 2 },
        cudaCores: 0,
        shaderProcessors: 3840,
      },
    },
    {
      name: "AMD Radeon RX 7900 XTX",
      price: 949,
      specs: {
        memory: { capacity: 24, type: "GDDR6", bandwidth: 960, bus: 384 },
        clock: { base: 1855, boost: 2498 },
        connector: "PCIe 4.0",
        power: { tdp: 355, connectors: "2x8-pin", recommended: 800 },
        display: { outputs: ["HDMI 2.1", "DisplayPort 2.1"], maxResolution: "7680x4320", maxDisplays: 4 },
        dimensions: { length: 287, slots: 2 },
        cudaCores: 0,
        shaderProcessors: 6144,
      },
    },
    {
      name: "AMD Radeon RX 7600",
      price: 269,
      specs: {
        memory: { capacity: 8, type: "GDDR6", bandwidth: 288, bus: 128 },
        clock: { base: 1720, boost: 2655 },
        connector: "PCIe 4.0",
        power: { tdp: 165, connectors: "1x8-pin", recommended: 550 },
        display: { outputs: ["HDMI 2.1", "DisplayPort 2.1"], maxResolution: "7680x4320", maxDisplays: 4 },
        dimensions: { length: 204, slots: 2 },
        cudaCores: 0,
        shaderProcessors: 2048,
      },
    },
    {
      name: "NVIDIA GeForce RTX 3060",
      price: 299,
      specs: {
        memory: { capacity: 12, type: "GDDR6", bandwidth: 360, bus: 192 },
        clock: { base: 1320, boost: 1777 },
        connector: "PCIe 4.0",
        power: { tdp: 170, connectors: "1x8-pin", recommended: 550 },
        display: { outputs: ["HDMI 2.1", "DisplayPort 1.4a"], maxResolution: "7680x4320", maxDisplays: 4 },
        dimensions: { length: 242, slots: 2 },
        cudaCores: 3584,
        shaderProcessors: 3584,
      },
    },
    {
      name: "AMD Radeon RX 6650 XT",
      price: 259,
      specs: {
        memory: { capacity: 8, type: "GDDR6", bandwidth: 280, bus: 128 },
        clock: { base: 2055, boost: 2635 },
        connector: "PCIe 4.0",
        power: { tdp: 180, connectors: "2x8-pin", recommended: 600 },
        display: { outputs: ["HDMI 2.1", "DisplayPort 1.4"], maxResolution: "7680x4320", maxDisplays: 4 },
        dimensions: { length: 220, slots: 2 },
        cudaCores: 0,
        shaderProcessors: 2048,
      },
    },
    {
      name: "NVIDIA GeForce RTX 4070 Ti Super",
      price: 799,
      specs: {
        memory: { capacity: 16, type: "GDDR6X", bandwidth: 672, bus: 256 },
        clock: { base: 2340, boost: 2610 },
        connector: "PCIe 4.0",
        power: { tdp: 285, connectors: "1x16-pin", recommended: 700 },
        display: { outputs: ["HDMI 2.1", "DisplayPort 1.4a"], maxResolution: "7680x4320", maxDisplays: 4 },
        dimensions: { length: 304, slots: 3 },
        cudaCores: 8448,
        shaderProcessors: 8448,
      },
    },
  ],

  cooling: [
    {
      name: "Noctua NH-D15",
      price: 100,
      specs: {
        type: "Air",
        sockets: ["LGA1700", "AM5", "AM4"],
        tdp: 250,
        noise: { min: 19.2, max: 24.6 },
        fan: { size: "140mm", count: 2, minRpm: 300, maxRpm: 1500, bearing: "SSO2" },
        radiator: { size: "None", thickness: 0 },
        dimensions: { height: 165, width: 150, depth: 161 },
        heatpipes: 6,
        argb: false,
      },
    },
    {
      name: "Corsair iCUE H150i Elite LCD",
      price: 280,
      specs: {
        type: "AIO Liquid",
        sockets: ["LGA1700", "AM5", "AM4"],
        tdp: 300,
        noise: { min: 10, max: 36 },
        fan: { size: "120mm", count: 3, minRpm: 396, maxRpm: 2250, bearing: "Magnetic Levitation" },
        radiator: { size: "360mm", thickness: 27 },
        dimensions: { height: 397, width: 120, depth: 27 },
        heatpipes: 0,
        argb: true,
      },
    },
    {
      name: "NZXT Kraken X63",
      price: 180,
      specs: {
        type: "AIO Liquid",
        sockets: ["LGA1700", "AM5", "AM4"],
        tdp: 250,
        noise: { min: 21, max: 36 },
        fan: { size: "140mm", count: 2, minRpm: 500, maxRpm: 1800, bearing: "Fluid Dynamic" },
        radiator: { size: "280mm", thickness: 30 },
        dimensions: { height: 315, width: 140, depth: 30 },
        heatpipes: 0,
        argb: true,
      },
    },
    {
      name: "be quiet! Dark Rock Pro 4",
      price: 90,
      specs: {
        type: "Air",
        sockets: ["LGA1700", "AM5", "AM4"],
        tdp: 250,
        noise: { min: 12.4, max: 24.3 },
        fan: { size: "135mm", count: 2, minRpm: 600, maxRpm: 1500, bearing: "Rifle" },
        radiator: { size: "None", thickness: 0 },
        dimensions: { height: 163, width: 140, depth: 146 },
        heatpipes: 7,
        argb: false,
      },
    },
    {
      name: "Cooler Master MasterLiquid ML360R",
      price: 150,
      specs: {
        type: "AIO Liquid",
        sockets: ["LGA1700", "AM5", "AM4"],
        tdp: 280,
        noise: { min: 6, max: 30 },
        fan: { size: "120mm", count: 3, minRpm: 650, maxRpm: 2000, bearing: "Rifle" },
        radiator: { size: "360mm", thickness: 27 },
        dimensions: { height: 397, width: 120, depth: 27 },
        heatpipes: 0,
        argb: true,
      },
    },
    {
      name: "ARCTIC Liquid Freezer II 280",
      price: 110,
      specs: {
        type: "AIO Liquid",
        sockets: ["LGA1700", "AM5", "AM4"],
        tdp: 250,
        noise: { min: 0.3, max: 22.5 },
        fan: { size: "140mm", count: 2, minRpm: 200, maxRpm: 1700, bearing: "Fluid Dynamic" },
        radiator: { size: "280mm", thickness: 38 },
        dimensions: { height: 317, width: 140, depth: 38 },
        heatpipes: 0,
        argb: false,
      },
    },
    {
      name: "Deepcool AK620",
      price: 55,
      specs: {
        type: "Air",
        sockets: ["LGA1700", "AM5", "AM4"],
        tdp: 260,
        noise: { min: 28.6, max: 28.6 },
        fan: { size: "120mm", count: 2, minRpm: 500, maxRpm: 1850, bearing: "Fluid Dynamic" },
        radiator: { size: "None", thickness: 0 },
        dimensions: { height: 160, width: 129, depth: 138 },
        heatpipes: 6,
        argb: false,
      },
    },
    {
      name: "Corsair iCUE H100i Elite Capellix",
      price: 140,
      specs: {
        type: "AIO Liquid",
        sockets: ["LGA1700", "AM5", "AM4"],
        tdp: 250,
        noise: { min: 10, max: 36 },
        fan: { size: "120mm", count: 2, minRpm: 396, maxRpm: 2250, bearing: "Magnetic Levitation" },
        radiator: { size: "240mm", thickness: 27 },
        dimensions: { height: 277, width: 120, depth: 27 },
        heatpipes: 0,
        argb: true,
      },
    },
    {
      name: "Thermalright Peerless Assassin 120 SE",
      price: 35,
      specs: {
        type: "Air",
        sockets: ["LGA1700", "AM5", "AM4"],
        tdp: 245,
        noise: { min: 22.6, max: 25.6 },
        fan: { size: "120mm", count: 2, minRpm: 500, maxRpm: 1500, bearing: "Sleeve" },
        radiator: { size: "None", thickness: 0 },
        dimensions: { height: 157, width: 130, depth: 135 },
        heatpipes: 6,
        argb: false,
      },
    },
    {
      name: "Lian Li Galahad 240",
      price: 100,
      specs: {
        type: "AIO Liquid",
        sockets: ["LGA1700", "AM5", "AM4"],
        tdp: 230,
        noise: { min: 24, max: 30 },
        fan: { size: "120mm", count: 2, minRpm: 600, maxRpm: 1900, bearing: "Fluid Dynamic" },
        radiator: { size: "240mm", thickness: 27 },
        dimensions: { height: 277, width: 120, depth: 27 },
        heatpipes: 0,
        argb: true,
      },
    },
  ],

  case: [
    {
      name: "NZXT H510",
      price: 80,
      specs: {
        formFactor: "Mid Tower",
        supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
        maxGpuLength: 381,
        maxCoolerHeight: 165,
        maxPsuLength: 180,
        driveBays: { bay35: 2, bay25: 2 },
        expansionSlots: 7,
        radiatorSupport: { front: "280mm" },
        frontPorts: ["USB-C", "USB-A", "Audio"],
        includedFans: 2,
        dimensions: { height: 428, width: 210, depth: 460 },
        sidePanel: "Tempered Glass",
      },
    },
    {
      name: "Corsair 4000D Airflow",
      price: 95,
      specs: {
        formFactor: "Mid Tower",
        supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
        maxGpuLength: 360,
        maxCoolerHeight: 170,
        maxPsuLength: 180,
        driveBays: { bay35: 2, bay25: 2 },
        expansionSlots: 7,
        radiatorSupport: { front: "360mm", top: "240mm" },
        frontPorts: ["USB-C", "USB-A", "Audio"],
        includedFans: 2,
        dimensions: { height: 466, width: 230, depth: 453 },
        sidePanel: "Tempered Glass",
      },
    },
    {
      name: "Fractal Design North",
      price: 140,
      specs: {
        formFactor: "Mid Tower",
        supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
        maxGpuLength: 355,
        maxCoolerHeight: 170,
        maxPsuLength: 175,
        driveBays: { bay35: 2, bay25: 2 },
        expansionSlots: 7,
        radiatorSupport: { front: "280mm", top: "240mm" },
        frontPorts: ["USB-C", "USB-A", "Audio"],
        includedFans: 2,
        dimensions: { height: 469, width: 215, depth: 425 },
        sidePanel: "Mesh",
      },
    },
    {
      name: "Lian Li O11 Dynamic",
      price: 160,
      specs: {
        formFactor: "Mid Tower",
        supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX", "E-ATX"],
        maxGpuLength: 422,
        maxCoolerHeight: 155,
        maxPsuLength: 220,
        driveBays: { bay35: 2, bay25: 4 },
        expansionSlots: 8,
        radiatorSupport: { front: "360mm", top: "360mm" },
        frontPorts: ["USB-C", "USB-A", "Audio"],
        includedFans: 0,
        dimensions: { height: 446, width: 272, depth: 446 },
        sidePanel: "Tempered Glass",
      },
    },
    {
      name: "Cooler Master NR200",
      price: 90,
      specs: {
        formFactor: "Small Form Factor",
        supportedFormFactors: ["Mini-ITX"],
        maxGpuLength: 330,
        maxCoolerHeight: 155,
        maxPsuLength: 130,
        driveBays: { bay35: 1, bay25: 2 },
        expansionSlots: 2,
        radiatorSupport: { front: "240mm" },
        frontPorts: ["USB-C", "USB-A"],
        includedFans: 2,
        dimensions: { height: 376, width: 185, depth: 185 },
        sidePanel: "Mesh",
      },
    },
    {
      name: "Phanteks Eclipse P500A",
      price: 130,
      specs: {
        formFactor: "Full Tower",
        supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX", "E-ATX"],
        maxGpuLength: 435,
        maxCoolerHeight: 192,
        maxPsuLength: 220,
        driveBays: { bay35: 2, bay25: 3 },
        expansionSlots: 7,
        radiatorSupport: { front: "360mm", top: "360mm" },
        frontPorts: ["USB-C", "USB-A", "Audio"],
        includedFans: 3,
        dimensions: { height: 480, width: 230, depth: 465 },
        sidePanel: "Tempered Glass",
      },
    },
    {
      name: "be quiet! Pure Base 500DX",
      price: 100,
      specs: {
        formFactor: "Mid Tower",
        supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
        maxGpuLength: 369,
        maxCoolerHeight: 190,
        maxPsuLength: 200,
        driveBays: { bay35: 2, bay25: 2 },
        expansionSlots: 7,
        radiatorSupport: { front: "360mm", top: "240mm" },
        frontPorts: ["USB-C", "USB-A", "Audio"],
        includedFans: 3,
        dimensions: { height: 463, width: 232, depth: 450 },
        sidePanel: "Tempered Glass",
      },
    },
    {
      name: "Thermaltake Core P3",
      price: 110,
      specs: {
        formFactor: "Mid Tower",
        supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
        maxGpuLength: 450,
        maxCoolerHeight: 180,
        maxPsuLength: 200,
        driveBays: { bay35: 2, bay25: 2 },
        expansionSlots: 7,
        radiatorSupport: { front: "360mm" },
        frontPorts: ["USB-A", "Audio"],
        includedFans: 1,
        dimensions: { height: 480, width: 252, depth: 537 },
        sidePanel: "Acrylic",
      },
    },
    {
      name: "Hyte Y60",
      price: 200,
      specs: {
        formFactor: "Mid Tower",
        supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
        maxGpuLength: 400,
        maxCoolerHeight: 170,
        maxPsuLength: 200,
        driveBays: { bay35: 0, bay25: 2 },
        expansionSlots: 7,
        radiatorSupport: { front: "360mm", top: "240mm" },
        frontPorts: ["USB-C", "USB-A"],
        includedFans: 0,
        dimensions: { height: 484, width: 230, depth: 470 },
        sidePanel: "Tempered Glass",
      },
    },
    {
      name: "SilverStone SG13",
      price: 55,
      specs: {
        formFactor: "Small Form Factor",
        supportedFormFactors: ["Mini-ITX"],
        maxGpuLength: 280,
        maxCoolerHeight: 61,
        maxPsuLength: 130,
        driveBays: { bay35: 0, bay25: 2 },
        expansionSlots: 2,
        radiatorSupport: {},
        frontPorts: ["USB-A"],
        includedFans: 1,
        dimensions: { height: 295, width: 210, depth: 350 },
        sidePanel: "Mesh",
      },
    },
  ],
};

async function getOrCreateDemoSeller() {
  let user = await UserModel.findOne({ username: "demo_seller" });
  if (!user) {
    user = await UserModel.create({
      username: "demo_seller",
      password: "DemoSeller123!",
      firstName: "Demo",
      lastName: "Seller",
      roles: ["seller"],
    });
    console.log("Created demo_seller user");
  } else {
    console.log("Reusing existing demo_seller user");
  }

  const existingProfile = await SellerModel.findOne({ user: user._id });
  if (!existingProfile) {
    await SellerModel.create({
      user: user._id,
      phone: "+1 555 0100",
      email: "demo_seller@example.com",
      address: {
        country: "USA",
        city: "Springfield",
        street: "123 Demo Street",
        zip: "00000",
      },
      warranty: {
        durationMonths: 24,
        accidentalDamage: false,
        wearAndTear: false,
        resolution: "repair_replace",
        shipping: "seller",
      },
      verified: true,
    });
    console.log("Created demo_seller Seller profile");
  } else {
    console.log("Reusing existing demo_seller Seller profile");
  }

  return user;
}

async function createPlaceholderImageKey(type) {
  const buffer = await sharp({
    create: {
      width: 600,
      height: 600,
      channels: 4,
      background: TYPE_COLORS[type],
    },
  })
    .png()
    .toBuffer();

  const [key] = await uploadFiles(
    [{ buffer, mimetype: "image/png", originalname: `${type}-placeholder.png` }],
    "products",
  );
  return key;
}

async function seed() {
  await mongoose.connect(process.env.DB_URI);
  console.log("Connected to MongoDB");

  const seller = await getOrCreateDemoSeller();

  for (const type of Object.keys(DATA)) {
    const imageKey = await createPlaceholderImageKey(type);
    let created = 0;

    for (const item of DATA[type]) {
      const exists = await ProductModel.findOne({
        seller: seller._id,
        type,
        name: item.name,
      });
      if (exists) continue;

      await ProductModel.create({
        type,
        name: item.name,
        price: item.price,
        stock: item.stock ?? 15,
        condition: item.condition ?? "new",
        images: [imageKey],
        specs: item.specs,
        seller: seller._id,
      });
      created += 1;
    }

    console.log(`${type}: created ${created}/${DATA[type].length} (rest already existed)`);
  }

  console.log("Seeding complete");
  await mongoose.connection.close();
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
